version: '3.1'
services:
    php73-apache:
        build:
            context: ../
            dockerfile: docker/php-apache/Dockerfile
        container_name: webchecker-php73-apache
        ports:
            - "8080:80"
        volumes:
            - ../:/var/www/html
            - ./php-apache/logs/apache:/var/log/apache2
            - ./php-apache/logs/php:/usr/local/etc/php/log
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal

    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8081:8080
        environment:
            ADMINER_DEFAULT_SERVER: mysql